#! /bin/sh

sxhkd -f 100 &

bspc config border_width        3
bspc config window_gap          8

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d I II III

bspc rule -a Gimp desktop=^8 state=floating follow=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a lxappearance state=floating
bspc rule -a xfce4-panel state=floating
bspc rule -a orage state=floating

bspc config bottom_padding 31
bspc config focused_border_color "#3a81cc"
bspc config normal_border_color "#444444"
bspc config urgent_border_color "#ff0000"
bspc config focus_follows_pointer true
bspc config leaf_monocle true

xsetroot -cursor_name left_ptr
sh ~/.fehbg
synclient tapbutton1=0 tapbutton2=0 tapbutton3=0 verttwofingerscroll=0 vertedgescroll=1 horizedgescroll=1 horizscrolldelta=10
urxvtd -q -f -o
compton --backend glx --vsync opengl-mswc &
#panel &
xfce4-panel &
