#! /bin/sh

sxhkd &

bspc monitor -d 00 01 10 11

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^4' state=floating follow=on
bspc rule -a Firefox desktop='^1'
bspc rule -a Lxappearance state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focused_border_color "#cecece"
bspc config normal_border_color "#000000"
bspc config urgent_border_color "#ff0000"
bspc config click_to_focus any
bspc config single_monocle true

mate-power-manager&
setxkbmap gb
xsetroot -cursor_name left_ptr
sh ~/.fehbg
volumeicon &
tint2 &
