#! /bin/sh

sxhkd &

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d I II III

bspc rule -a Gimp desktop=^3 state=floating follow=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config bottom_padding 30
bspc config focused_border_color "#4084d6"
bspc config normal_border_color "#444444"
bspc config urgent_border_color "#ff0000"
bspc config focus_follows_pointer true
bspc config single_monocle true

xsetroot -cursor_name left_ptr
sh ~/.fehbg
urxvtd -q -f -o
volumeicon &
tint2 &
